/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lan.luca.iss2021_resumablebw;

import lan.luca.iss2021_resumablebw.annotations.ArilRobotSpec;
import lan.luca.iss2021_resumablebw.consolegui.ConsoleGui;
import lan.luca.iss2021_resumablebw.interaction.IssOperations;
import lan.luca.iss2021_resumablebw.supports.IssCommSupport;
import lan.luca.iss2021_resumablebw.supports.RobotApplicationStarter;
import lan.luca.iss2021_resumablebw.wenv.RobotInputController;

@ArilRobotSpec
public class ClientBoundaryGui {
    private final RobotInputController controller;
    private ConsoleGui consoleGui;

    public ClientBoundaryGui(IssOperations rs) {
        IssCommSupport rsComm = (IssCommSupport) rs;
        controller = new RobotInputController(rsComm, true, true);
        rsComm.registerObserver(controller);
        System.out.println("ClientBoundaryGui | CREATED with rsComm=" + rsComm);
    }

    private void start() {
        consoleGui = new ConsoleGui(controller);
        controller.doBoundary();
    }

    public static void main(String[] args) {
        try {
            System.out.println("ClientBoundaryWebsockBasicAsynch | main start n_Threads=" + Thread.activeCount());
            Object appl = RobotApplicationStarter.createInstance(ClientBoundaryGui.class);
            System.out.println("ClientBoundaryWebsockBasicSynch  | appl n_Threads=" + Thread.activeCount());
            ((ClientBoundaryGui) appl).start();
            System.out.println("ClientBoundaryWebsockBasicAsynch | main end n_Threads=" + Thread.activeCount());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}



