/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lan.luca.iss2021_resumablebw;

import static org.junit.Assert.*;

public class AppTest {
    //@Test
    public void testAppHasAGreeting() {

    }
}
